// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtouAJD2PKk1T3IbhvYeQ5XaB7lsQ4LKA',
    appId: '1:688280990116:web:2801f0485ac5ed834b5131',
    messagingSenderId: '688280990116',
    projectId: 'campuswatch-20e6f',
    authDomain: 'campuswatch-20e6f.firebaseapp.com',
    storageBucket: 'campuswatch-20e6f.firebasestorage.app',
    measurementId: 'G-G0R2LDS6CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABAZYIvIdIzPhIemFlfBZLKmvFmHIHyas',
    appId: '1:688280990116:android:edf7d9ea5cba57e24b5131',
    messagingSenderId: '688280990116',
    projectId: 'campuswatch-20e6f',
    storageBucket: 'campuswatch-20e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWzIuYZ-TFKH4q3usAMqWFxoBJQhuISU0',
    appId: '1:688280990116:ios:a958094fc9be32704b5131',
    messagingSenderId: '688280990116',
    projectId: 'campuswatch-20e6f',
    storageBucket: 'campuswatch-20e6f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWzIuYZ-TFKH4q3usAMqWFxoBJQhuISU0',
    appId: '1:688280990116:ios:a958094fc9be32704b5131',
    messagingSenderId: '688280990116',
    projectId: 'campuswatch-20e6f',
    storageBucket: 'campuswatch-20e6f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtouAJD2PKk1T3IbhvYeQ5XaB7lsQ4LKA',
    appId: '1:688280990116:web:5e598b5126deb4014b5131',
    messagingSenderId: '688280990116',
    projectId: 'campuswatch-20e6f',
    authDomain: 'campuswatch-20e6f.firebaseapp.com',
    storageBucket: 'campuswatch-20e6f.firebasestorage.app',
    measurementId: 'G-BR9SMB31JV',
  );
}
